src/Easyb/MainBundle/Form/Type/ArticleFileType.php
<?php
/**
 * Created by PhpStorm.
 * User: ivan
 * Date: 15.08.14
 * Time: 13:35
 */

namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class ArticleFileType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('displayName', null, [
                'required' => true,
                'label'    => 'Название'
            ])
            ->add('file', 'file', [
                'required' => true,
                'label'    => 'Файл'
            ])
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array('data_class' => 'Easyb\\MainBundle\\Entity\\ArticleFile'));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "article_file_type";
    }
}

src/Easyb/MainBundle/Form/Type/CategoryType.php
<?

namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

/*
use Test\TestBundle\Entity\City;
use Test\TestBundle\Entity\Country;
use Test\TestBundle\Entity\State;
*/


class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('category', 'entity', array(
                'class' => 'MainBundle:Category',
                'placeholder' => '',
            ));

        $builder->addEventListener(
            FormEvents::PRE_SET_DATA,
            function (FormEvent $event) {
                $form = $event->getForm();

                // this would be your entity, i.e. SportMeetup
                $data = $event->getData();

                $category = $data->getSport();
                $subcategories = null === $category ? array() : $category->getAvailablePositions();

                $form->add('subcategory', 'entity', array(
                    'class' => 'MainBundle:Category',
                    'placeholder' => '',
                    'choices' => $subcategories,
                ));
            }
        );
    }


    public function getName()
    {
        return 'category';
    }

    public function getDefaultOptions(array $options)
    {
        return array('data_class' => 'Easyb\MainBundle\Entity\Category');
    }
}

src/Easyb/MainBundle/Form/Type/FrontendSearchType.php
<?php

namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\HttpFoundation\Session\Session;

use Easyb\AdvertBundle\Entity\AbstractAdvert;

class FrontendSearchType extends AbstractType
{
    protected $session;

    /**
     * @param \Symfony\Component\HttpFoundation\Session\Session $session
     */
    public function __construct(Session $session)
    {
        $this->session = $session;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
          ->add('text', null, array('required' => false, 'data' => $this->session->get('search_text') ? $this->session->get('search_text') : ''))
          ->add('categoryId', 'hidden', array('data' => $this->session->get('categoryId') ? $this->session->get('categoryId') : ''))
          ->add('subcategoryId', 'hidden', array('data' => $this->session->get('subcategoryId') ? $this->session->get('subcategoryId') : ''))
          ->add('advertTypeId', 'hidden', array('data' => $this->session->get('advertTypeId') ? $this->session->get('advertTypeId') : AbstractAdvert::OFFER))
          ->add('cityId', 'hidden', array('data' => $this->session->get('cityId') ? $this->session->get('cityId') : ''));
    }
    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "search_type";
    }
}

src/Easyb/MainBundle/Form/Type/GetContatType.php
<?php
/**
 * Created by IntelliJ IDEA.
 * User: User
 * Date: 13.03.2016
 * Time: 15:43
 */

namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;


class GetContatType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('captcha', 'genemu_recaptcha')
        ;
    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {

    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "get_contacts";
    }
}

src/Easyb/MainBundle/Form/Type/HelpType.php
<?php
namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

/**
 * Class HelpType
 *
 * @package Easyb\MainBundle\Form\Type
 */
class HelpType extends AbstractType
{

    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add('email', null, array ('label'    => 'Укажите Ваш Email для обратной связи',
                                            'required' => true

        ));
        $builder->add('text', null, array ('label'    => 'Если Вы хотите сообщить об ошибке - большая просьба: прикладывайте ссылки с багами, пожалуйста. Спасибо.',
                                           'required' => true
        ));
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array ('class' => 'Easyb\\MainBundle\\Entity\\Help'));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'help';
    }
}

src/Easyb/MainBundle/Form/Type/JobChoiceType.php
<?php

namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;

/**
 * class JobChoiceType
 */
class JobChoiceType extends AbstractType
{
    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "job_choice";
    }

    public function getParent()
    {
        return 'entity';
    }
}

src/Easyb/MainBundle/Form/Type/UploadbannerType.php
<?php
/**
 * User: scorp
 * Date: 14.07.13
 * Time: 23:14
 */
namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormError as FormError;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\Form\CallbackValidator as CallbackValidator;

/**
 * class Uploadify
 *
 * rendering file field type with uploadify functionality
 */
class UploadbannerType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setAttribute('widget', $options['widget'])
            ->setAttribute('uploaderPath', $options['uploaderPath'])
            ->setAttribute('success', $options['success'])
            ->setAttribute('formData', $options['formData'])
            ->setAttribute('multi', $options['multi'])
            ->setAttribute('swfPath', $options['swfPath'])
            ->setAttribute('fileTypeExts', $options['fileTypeExts']);
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['uploaderPath'] = $options['uploaderPath'];
        $view->vars['success'] = $options['success'];
        $view->vars['swfPath'] = $options['swfPath'];
        $view->vars['fileTypeExts'] = $options['fileTypeExts'];
        $view->vars['multi'] = $options['multi'];
        $view->vars['formData'] = $options['formData'];
    }


    /**
     * @param \Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array (
            'widget'       => 'file',
            'swfPath'      => '',
            'multi'        => false,
            'fileTypeExts' => '*.jpg; *.png;*.jpeg; *.gif; *GIF; *.JPEG; *.JPG; *.PNG; *.swf; *.SWF;',
            'success'      => '',
            'formData'     => array (),
            'uploaderPath' => ''
        ));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "uploadbanner";
    }
}

src/Easyb/MainBundle/Form/Type/UploadifyType.php
<?php
/**
 * Created by JetBrains PhpStorm.
 * User: scorp
 * Date: 10.06.13
 * Time: 18:53
 * To change this template use File | Settings | File Templates.
 */
namespace Easyb\MainBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormError as FormError;
use Symfony\Component\Form\FormView;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\Form\CallbackValidator as CallbackValidator;

/**
 * class Uploadify
 *
 * rendering file field type with uploadify functionality
 */
class UploadifyType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->setAttribute('widget', $options['widget'])
            ->setAttribute('uploaderPath', $options['uploaderPath'])
            ->setAttribute('success', $options['success'])
            ->setAttribute('formData', $options['formData'])
            ->setAttribute('multi', $options['multi'])
            ->setAttribute('swfPath', $options['swfPath'])
            ->setAttribute('fileTypeExts', $options['fileTypeExts']);
    }

    /**
     * {@inheritdoc}
     */
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        $view->vars['uploaderPath'] = $options['uploaderPath'];
        $view->vars['success'] = $options['success'];
        $view->vars['swfPath'] = $options['swfPath'];
        $view->vars['fileTypeExts'] = $options['fileTypeExts'];
        $view->vars['multi'] = $options['multi'];
        $view->vars['formData'] = $options['formData'];
    }


    /**
     * @param \Symfony\Component\OptionsResolver\OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array (
            'widget'       => 'file',
            'swfPath'      => '',
            'multi'        => false,
            'fileTypeExts' => '*.jpg; *.png;*.jpeg; *.JPEG; *.JPG; *.PNG;',
            'success'      => '',
            'formData'     => array (),
            'uploaderPath' => ''
        ));
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "uploadify";
    }
}

src/Easyb/MainBundle/Resources/views/Form/form_div_layout.html.twig
{% block form_widget_compound %}
    {% spaceless %}
        <div {{ block('widget_container_attributes') }}>
            {% if form.parent is empty %}
                {{ form_errors(form) }}
            {% endif %}
            {{ block('form_rows') }}
            {{ form_rest(form) }}
        </div>
    {% endspaceless %}
{% endblock form_widget_compound %}


{% block form_row %}
    {% spaceless %}
        {{ form_label(form) }}
        <div class="input  {% if errors|length > 0 %} error {% endif %}">
            {{ form_widget(form) }}
            {{ form_errors(form) }}
        </div>
    {% endspaceless %}
{% endblock form_row %}


{% block form_errors %}
    {% spaceless %}
        {% if errors|length > 0 %}
            <div class="err-text">
                {% for error in errors %}
                    {{ error.message }}
                {% endfor %}
            </div>
        {% endif %}
    {% endspaceless %}
{% endblock form_errors %}

{% block form_label %}
    {% spaceless %}
        {% if label is not sameas(false) %}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('label'))|trim}) %}
            {% if not compound %}
                {% set label_attr = label_attr|merge({'for': id}) %}
            {% endif %}
            {% if required %}
                {% set label_attr = label_attr|merge({'class': (label_attr.class|default('label') ~ ' required')|trim}) %}
            {% endif %}
            {% if label is empty %}
                {% set label = name|humanize %}
            {% endif %}
            <label {% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %} >
                {{ label|trans({}, translation_domain) -}}
                {%- if required %}
                    <span class="red">*</span>
                {%- endif -%}
            </label>
        {% endif %}
    {% endspaceless %}
{% endblock form_label %}

{% block job_choice_widget %}
    {% spaceless %}
        {% if expanded %}
            {{ block('choice_widget_expanded') }}
        {% else %}
            {{ block('choice_widget_collapsed') }}
        {% endif %}
    {% endspaceless %}
    {#<br/>
    <div class="job_info"></div>
    {% if form.parent.children["category"] is defined %}
        {% set widget_id = form.parent.children["category"].vars.id %}
    {% else %}
        {% set widget_id = "form" %}
    {% endif %}
    <script type="text/javascript">
        $('form').ready(function () {
            $.ajax({
                type: "POST",
                url: '{{ path('get_job_ajax') }}',
                data: {
                    jobId: $(this).find(":selected").attr('value')
                },
                success: function (data) {
                    if (data.jobInfoTemplate) {
                        $('.job_info').html(data.jobInfoTemplate);
                    } else {
                        $('.job_info').empty();
                    }

                    updateCategories(data);
                }
            });
        });

        function updateCategories(data) {
            var newOptions = data.categories;

            var $el = $("#offer_type_category");
            $el.empty(); // remove old options
            $.each(newOptions, function (value, key) {
                $el.append($("<option></option>")
                        .attr("value", value).text(key));
            });
            $el.parent().find(".selectArea").remove();
            $el.removeClass("outtaHere").customSelect();
        }

        $('#{{ id }}').on('change', function () {
            $.ajax({
                type: "POST",
                url: '{{ path('get_job_ajax') }}',
                data: {
                    jobId: $(this).find(":selected").attr('value')
                },
                success: function (data) {
                    if (data.jobInfoTemplate) {
                        $('.job_info').html(data.jobInfoTemplate);
                    } else {
                        $('.job_info').empty();
                    }
                    updateCategories(data);
                }
            });
        });
    </script>#}
{% endblock job_choice_widget %}

{% block file_collection_widget %}
    {% spaceless %}
        {% if prototype is defined %}
            {% set attr = attr|merge({'data-prototype': block('collection_item_widget') }) %}
        {% endif %}
        <table class="file_collection" {% if prototype is defined %}data-prototype="{{ attr['data-prototype'] }}{% endif %}">
            {% for rows in form %}
                <tr class="file_form">
                    {% set fieldNum = 1 %}
                    {% for row in rows %}
                        {{ block('file_row_widget') }}
                    {% endfor %}
                </tr>
                {{ form_errors(rows.displayName) }}
            {% endfor %}
            {{ form_rest(form) }}
        </table>
    {% endspaceless %}
{% endblock %}

{% block collection_rest %}
{% endblock %}

{% block collection_item_widget %}
    {% spaceless %}
        {% set fieldNum = 1 %}
        {% for row in prototype %}
            {{ block('file_row_widget') }}
            {{ form_errors(row) }}
        {% endfor %}
        {{ form_errors(prototype.displayName) }}
    {% endspaceless %}
{% endblock %}

{% block file_widget %}
    {% if file_id is defined and file_id is not null and get_required is defined %}
        <td class="file_info" data-size="{{ file_size }}" data-ext="jpg" data-required="{{ get_required }}">
            {#<a href="{{ path('save_file', {'id' : file_id}) }}" target="_blank">
                {{- file_name | truncate(30) -}}
            </a>#}
            <span class="opt-link">{{ file_name }}</span>
            <span> | </span>
            <span>
                {{- _self.bytesToSize(file_size) -}}
            </span>
        </td>
        <td class="file_actions">
            <div class="action">
                <a href="{{ path('preview_file', {'id' : file_id}) }}" target="_blank">Просмотр</a>
            </div>
        </td>
    {% else %}
        <td class="file_info">
            <span class="opt-link">Загрузить файл</span>
            <input type="file" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}>
        </td>
        <td class="file_actions">

        </td>
    {% endif %}
{% endblock %}

{% block file_row_widget %}
    {% if row.vars.name == 'file' %}
        {{ form_widget(row) }}
    {% elseif row.vars.name == 'required' %}
        {{ form_widget(row) }}
    {% else %}
        <td class="file_name">
            {{- form_widget(row) -}}
        </td>
    {% endif %}
    {% set fieldNum = fieldNum + 1 %}
{% endblock file_row_widget %}

    {% block uploadify_widget %}
        {% spaceless %}
            <a href="#" {{ block('widget_attributes') }}></a>
            <script type="text/javascript">
                $(document).ready(function () {
                    $('#{{ id }}').uploadify({
                        'hideButton': true,
                        'wmode': 'transparent',
                        'height': '20',
                        'width': '60',
                        'removeTimeout': 0,
                        'successTimeout': 10,
                        'fileObjName': 'filedata',
                        'swf': '{{ asset(swfPath) }}',
                        'uploader': '{{ path(uploaderPath) }}',
                        'formData': {
                            {% for key,data in formData %}
                            '{{ key }}': {{ data }},
                            {% endfor %}
                        },
                        'multi': {% if multi %}true{% else %}false{% endif %},
                        'fileTypeExts': '{{ fileTypeExts }}',
                        'fileSizeLimit': '5MB',
                        'buttonText': '<span class="opt-link" id="load-photo">Загрузить</span>',
                        'onUploadSuccess': function (file, data, response) {
                            data = $.parseJSON(data);
                            addPhoto(data);
                        },
                        'onUploadError': function (file, errorCode, errorMsg, errorString) {
                            console.log(errorMsg);
                            console.log(errorString);
                            if (errorString == 'Cancelled') {
                                alert('Загрузка фото прервана');
                            } else {
                                $('body').append($('#popupError'));
                                $('#popupError').show();
                            }
                        }
                    });
                });
            </script>
            <div class="modal" id="popupError" style="display: none">
                Ошибка
            </div>
        {% endspaceless %}
    {% endblock %}


    {% macro bytesToSize(bytes) %}
        {% spaceless %}
            {% set kilobyte = 1024 %}
            {% set megabyte = kilobyte * 1024 %}
            {% set gigabyte = megabyte * 1024 %}
            {% set terabyte = gigabyte * 1024 %}

            {% if bytes < kilobyte %}
                {{ bytes ~ ' B' }}
            {% elseif bytes < megabyte %}
                {{ (bytes / kilobyte)|number_format(2, '.') ~ ' KB' }}
            {% elseif bytes < gigabyte %}
                {{ (bytes / megabyte)|number_format(2, '.') ~ ' MB' }}
            {% elseif bytes < terabyte %}
                {{ (bytes / gigabyte)|number_format(2, '.') ~ ' GB' }}
            {% else %}
                {{ (bytes / terabyte)|number_format(2, '.') ~ ' TB' }}
            {% endif %}
        {% endspaceless %}
    {% endmacro %}

{#
{% block choice_widget_options %}
{% spaceless %}
    {% for group_label, choice in options %}
        {% if choice is iterable %}
            <optgroup label="{{ group_label|trans({}, translation_domain) }}">
                {% set options = choice %}
                {{ block('choice_widget_options') }}
            </optgroup>
        {% else %}
            <option value="{{ choice.value }}"
            {% if choice is selectedchoice(value) %}
            selected="selected"
            {% endif %}
            {% if choice.attr is defined %}
                {% for attrname, attrvalue in choice.attr %}
                    {% if attrname in ['title'] %}
                        {{ attrname }}="{{ attrvalue|trans({}, translation_domain) }}"
                    {% else %}
                        {{ attrname }}="{{ attrvalue }}"
                        {% endif %}
                    {% endfor %}
            {% endif %}
            >
            {{ choice.label|trans({}, translation_domain) }}
            </option>
        {% endif %}
    {% endfor %}
{% endspaceless %}
{% endblock choice_widget_options %}
#}