src/Easyb/AdvertBundle/Entity/AdvertFile.php
<?php

namespace Easyb\AdvertBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\Validator\Constraints as Assert;

use Easyb\UserBundle\Entity\Job;

/**
 * AdvertFile
 *
 * @ORM\Entity
 * @ORM\Table(name="advert_file")
 * @ORM\HasLifecycleCallbacks
 */
class AdvertFile
{
    public static $filesTypes = [
        'doc' => 'doc',
        'docx' => 'docx',
        'docm' => 'docm',
        'txt' => 'txt',
        'xlsx' => 'xlsx',
        'xlsb' => 'xlsb',
        'xls' => 'xls',
        'pptx' => 'pptx',
        'pptm' => 'pptm',
        'ppt' => 'ppt',
        'pdf' => 'pdf',
        'gif' => 'gif',
        'jpeg' => 'jpeg',
        'jpg' => 'jpg',
        'png' => 'png',
        'bmp' => 'bmp',
        'pps' => 'pps'
    ];

    /**
     * @var integer
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255)
     */
    private $name;

    /**
     * @var string
     *
     * @ORM\Column(name="display_name", type="string", length=255)
     * @Assert\NotBlank(message="Введите имя файла")
     */
    private $displayName;

    /**
     * @var AbstractAdvert $advert
     *
     * @ORM\ManyToOne(targetEntity="Easyb\AdvertBundle\Entity\AbstractAdvert", inversedBy="files")
     * @ORM\JoinColumn(name="advert_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $advert;

    /**
     * @var AbstractAdvert $advert
     *
     * @ORM\ManyToOne(targetEntity="Easyb\AdvertBundle\Entity\Reaction", inversedBy="files")
     * @ORM\JoinColumn(name="reaction_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $reaction;

    /**
     * @var AbstractAdvert $advert
     *
     * @ORM\ManyToOne(targetEntity="Easyb\AdvertBundle\Entity\Proposal", inversedBy="files")
     * @ORM\JoinColumn(name="proposal_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $proposal;


    /**
     * @var AbstractAdvert $advert
     *
     * @ORM\ManyToOne(targetEntity="Easyb\UserBundle\Entity\Job", inversedBy="files")
     * @ORM\JoinColumn(name="job_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $job;

    /**
     * @var AbstractAdvert $advert
     *
     * @ORM\ManyToOne(targetEntity="Easyb\AdvertBundle\Entity\Demand", inversedBy="inviteFile")
     * @ORM\JoinColumn(name="demand_id", referencedColumnName="id", onDelete="CASCADE")
     */
    private $demand;

    /**
     * @Assert\File(
     *     maxSize = "10240k",
     *     maxSizeMessage = "Максимальный размер 10Мб"
     * )
     *
     * @var string
     */
    private $file;

    /**
     * @var integer
     * @ORM\Column(name="required", type="integer", options={"default" = 0})
     */
    private $required;

    public function __construct()
    {
        $this->required = 0;
    }

    /**
     * Get id
     *
     * @return integer
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Get name
     *
     * @return string
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return AdvertFile
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get displayName
     *
     * @return string
     */
    public function getDisplayName()
    {
        return $this->displayName;
    }

    /**
     * Set displayName
     *
     * @param string $displayName
     * @return AdvertFile
     */
    public function setDisplayName($displayName)
    {
        $this->displayName = $displayName;

        return $this;
    }

    /**
     * @return string
     */
    public function getFile()
    {
        return $this->file;
    }

    /**
     * @param string $file
     */
    public function setFile($file)
    {
        $this->file = $file;
    }

    /**
     * Get advert
     *
     * @return \Easyb\AdvertBundle\Entity\AbstractAdvert
     */
    public function getAdvert()
    {
        return $this->advert;
    }

    /**
     * Set advert
     *
     * @param \Easyb\AdvertBundle\Entity\AbstractAdvert $advert
     *
     * @return AdvertFile
     */
    public function setAdvert(AbstractAdvert $advert = null)
    {
        $this->advert = $advert;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getReaction()
    {
        return $this->reaction;
    }

    /**
     * @param mixed $reaction
     */
    public function setReaction(Reaction $reaction = null)
    {
        $this->reaction = $reaction;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getProposal()
    {
        return $this->proposal;
    }

    /**
     * @param mixed $proposal
     */
    public function setProposal(Proposal $proposal = null)
    {
        $this->proposal = $proposal;

        return $this;
    }

    /**
     * @return string
     */
    public function __toString()
    {
        return $this->displayName;
    }

    /**
     * @ORM\PreFlush()
     */
    public function upload()
    {
        // the file property can be empty if the field is not required

        if (null === $this->file) {
            return;
        }


        if ($this->name) {
            $this->removeUpload();
        }

        $ext = $this->file->guessClientExtension();

        $name = uniqid() . '.' . $ext;
        $this->checkDirectory($this->getUploadRootDir());
        $this->file->move($this->getUploadRootDir(), $name);
        $this->setName($name);

        $this->file = null;
    }

    /**
     * @ORM\PostRemove()
     */
    public function removeUpload()
    {
        if ($file = $this->getAbsolutePath()) {
            //unlink($file);
        }
        $this->name = null;
    }

    /**
     * @return null|string
     */
    public function getAbsolutePath()
    {
        return null === $this->name ? null : $this->getUploadRootDir() . '/' . $this->name;
    }

    /**
     * @return string
     */
    protected function getUploadRootDir()
    {
        return __DIR__ . '/../../../../web' . $this->getUploadDir();
    }

    /**
     * @return string
     */
    protected function getUploadDir()
    {
        return '/upload/files';
    }

    private function checkDirectory($directory)
    {
        if (!is_dir($directory)) {
            if (false === @mkdir($directory, 0777, true)) {
                throw new FileException(sprintf('Unable to create the "%s" directory', $directory));
            }
        } elseif (!is_writable($directory)) {
            throw new FileException(sprintf('Unable to write in the "%s" directory', $directory));
        }
    }

    public function getPublicName()
    {
        $ext = end((explode(".", $this->name)));
        if ($this->advert != null) {
            $name = $this->advert->getJob()->getName();
        } elseif ($this->reaction != null) {
            $name = $this->reaction->getJob()->getName();
        } elseif ($this->demand != null) {
            $name = $this->demand->getJob()->getName();
        } elseif ($this->file == null) {
            $name = $this->name;
        } else {
            //$name = $this->getJob()->getName();
        }
        return $name . "_" . $this->displayName . "." . $ext;
    }

    /**
     * @return mixed
     */
    public function getJob()
    {
        return $this->job;
    }

    /**
     * @param mixed $reaction
     */
    public function setJob(Job $job = null)
    {
        $this->job = $job;

        return $this;
    }

    public function getWebPath()
    {
        return null === $this->name
            ? null
            : $this->getUploadDir() . '/' . $this->name;
    }


    public function getFileSize()
    {
        /*if ($this->file != null) {


        } else {
            $filesize = 0;
        }*/
        $filesize = filesize($this->getAbsolutePath());
        //$filesize = 0;
        return $filesize;
    }

    private $tempName;

    public function getTempName()
    {
        return $this->tempName;
    }

    public function setTempName($tempname)
    {
        $this->tempName = $tempname;
        return $this;
    }

    /**
     * @return boolean
     */
    public function getRequired()
    {
        return $this->required;
    }

    /**
     * @param boolean $required
     */
    public function setRequired($required)
    {
        $this->required = $required;
        return $this;
    }

    /**
     * @return Demand
     */
    public function getDemand()
    {
        return $this->demand;
    }

    /**
     * @param mixed $demand
     */
    public function setDemand($demand)
    {
        $this->demand = $demand;
        return $this;
    }
}

src/Easyb/AdvertBundle/Resources/views/Advert/advert.html.twig
{% extends "EasybMainBundle:Frontend:layout.html.twig" %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript" src="{{ asset('bundles/easybadvert/js/upload.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/easybadvert/js/jquery.numeric.min.js') }}"></script>
    <script type="text/javascript" src="{{ asset('bundles/easybadmin/js/plugins/forms/ckeditor/ckeditor.js') }}"></script>
{% endblock %}

{% block content %}
    <nav class="path">
        {{ wo_render_breadcrumbs() }}
    </nav>
    <h1>{% block advert_header -%}{%- endblock %}</h1>
    <div class="parts">
        <section class="">
            {# <form action="{{ savePath }}" method="post" {{ form_enctype(form) }}>#}
            {{ form_start(form) }}
            <fieldset>
                <ul class="form html-input">
                    <li class="parts">
                        <div class="big_half" id="job-part">
                            {{ form_row(form.name) }}
                        </div>
                    </li>
                    <li class="parts">
                        <div class="big_half" id="job-part">
                            <label class="label{% if form.job.vars.errors is not empty %} error{% endif %}">{{ form_label(form.job) }}</label>
                                <span id="job-help" class="info-pic">
                                    <span class="pic"></span>
                                    <span class="popup">
                                        <a href="/profile/job/add">Добавить место работы</a>
                                        Вы сможете в личном кабинете<span class="arr">
                                        </span>
                                    </span><!-- end .popup-->
                                </span>
                            {{ form_widget(form.job) }}
                            {{ form_errors(form.job) }}
                        </div>
                    </li>
                    <li class="parts">
                        <div class="half">
                            <label class="label{% if form.category.vars.errors is not empty %} error{% endif %}">{{ form_label(form.category) }}</label>
                            {{ form_widget(form.category) }}
                            {{ form_errors(form.category) }}
                        </div>
                        <div class="half">
                            <label class="label{% if form.subcategory.vars.errors is not empty %} error{% endif %}">{{ form_label(form.subcategory) }}</label>
                            {{ form_widget(form.subcategory) }}
                            {{ form_errors(form.subcategory) }}
                        </div>
                    </li>

                    {% block advert_timing -%}

                    {%- endblock %}

                    <li class="html-input">
                        {% spaceless %}
                            {% block advert_text_help -%}
                                Кратко изложите суть Вашего коммерческого предложения: что предлагаете, уникальность, выгода, почему именно Ваше предложение и т.д. Пожалуйста соблюдайте <a class="thickbox" href="{{ path('show_page', {'link': 'add_rules'}) }}?height=750&width=500&modal=true">правила</a> по размещению информации на сайте.
                            {%- endblock %}
                            <span class="red">*</span>
                            <div class="{% if errors is not empty %} error {% endif %}">
                                {{ form_widget(form.text) }}
                                {{ form_errors(form.text) }}
                            </div>
                        {% endspaceless %}
                    </li>
                    {% block required_docs %}

                    {% endblock %}
                    <li class="html-input attachFiles">
                        {% block advert_files_help -%}
                            Вы можете прикрепить к своему предложению Презентацию, Прайс-лист и тд.<br/>
                            Внимание! Прикреплению подлежат файлы расширений Word, Excel, Power Point, PDF-документы и Фотоизображения.<br/>
                            Суммарный объем файлов не должен превышат 30 Мб<br/>
                            Объем одного файла не должен превышать 10 Мб
                        {%- endblock %}
                        {#<span>Выберите файл и дайте ему имя</span>#}
                        <div class="files ">
                            {{ form_widget(form.files) }}
                        </div>
                        {{ form_errors(form['files']) }}
                        {% for error in form.vars.errors %}
                            <div class="red">{{ error.getMessage() }}</div>
                        {% endfor %}
                    </li>
                    <li class="form_meta">
                        {{ form_row(form.metaDescription) }}
                    </li>
                    <li class="submit">
                        <button type="submit">Опубликовать</button>
                    </li>
                </ul>
            </fieldset>
            {{ form_end(form) }}
        </section>
    </div>

    <script type="text/javascript">
        $(document).ready(function () {
            if ($("#offer_type_subcategory").val() == '') reloadCategories();


            $(document).on("submit", "form", window.advert.validate_form);
            $('.demand-timing-wrapper > div > input').numeric();

            if (!$('#job-part').find('.selectText').html()) {
                $('#job-part').find('.selectText').html('<div style="color: white">.</div>');
            }


            $(document).on("submit", "form", function () {
                if (!validate_form()) {
                    return false;
                }
            });

            function parseDate(date) {
                var dateString = date;
                var reggie = /(\d{2}).(\d{2}).(\d{4}) (\d{2}):(\d{2})/;
                var dateArray = reggie.exec(dateString);
                var dateObject = new Date(
                        (+dateArray[3]),
                        (+dateArray[2]) - 1, // Careful, month starts at 0!
                        (+dateArray[1]),
                        (+dateArray[4]),
                        (+dateArray[5])
                );


                return dateObject;
            }

            function validate_form() {
                if (parseDate($('#demand_type_expireAt').val()) < (new Date())) {
                    $(".time_error .red").text("Некорректная дата").show();
                    return false;
                }

                if (parseDate($('#demand_type_expireAt').val()) < current_date) {
                    $(".time_error .red").text("Вы можете продлить процедуру сбора заявок, но укорачивать ее запрещено").show();
                    return false;
                }


                return true;
            }

            function reloadCategories($selector) {
                var $category = $('#offer_type_category');
                var $subcategory = $('#offer_type_subcategory');
                var $form = $("form");
                var data = {};
                data[$category.attr('name')] = $category.val();
                $.ajax({
                    url: $form.attr('action'),
                    type: $form.attr('method'),
                    data: data,
                    success: function (html) {
                        $subcategory.parent().find(".selectArea").remove();
                        $subcategory.replaceWith(function () {
                                    var $select = $(html).find('#offer_type_subcategory');

                                    $select.find('option[value=""]').remove();
                                    return $select;
                                }
                        ).customSelect();
                    }
                });
            }

            $('#offer_type_category').change(function () {
                reloadCategories();
            });


        });
    </script>
    {% block extend_scripts %}
    {% endblock %}

{% endblock %}

src/Easyb/AdvertBundle/Resources/views/Advert/previewFile.html.twig
{% extends "EasybMainBundle:Frontend:layout.html.twig" %}

{% block content %}
    <h1>{{ file.displayName }}</h1>

    <div class="parts">
        {% if type %}
            <iframe style="width: 100%; height: 800px;" src="http://docs.google.com/viewer?url=http://{{ file_path }}&embedded=true"></iframe>
        {% else %}
            <img style="width: 100%" src="{{ file.webPath }}">
        {% endif %}
    </div>
{% endblock %}